// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = "ru";

export type Locales = "ru";

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
	/**
	 * П​р​и​в​е​т​,​ ​w​o​r​l​d
	 */
	hi: string;
};

export type TranslationFunctions = {
	/**
	 * Привет, world
	 */
	hi: () => LocalizedString;
};

export type Formatters = {};
