// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ru'

export type Locales =
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Д​о​б​р​о​ ​п​о​ж​а​л​о​в​а​т​ь​!​
​
​•​ ​Т​е​к​у​щ​а​я​ ​в​е​р​с​и​я​ ​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​<​a​ ​c​l​a​s​s​=​"​t​g​-​t​e​x​t​-​l​i​n​k​"​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​M​S​D​-​I​n​c​o​r​p​o​r​a​t​e​d​/​M​S​D​B​o​t​T​e​l​e​g​r​a​m​"​>​M​S​D​B​o​t​<​/​a​>​<​/​b​>​ ​—​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​v​e​r​s​i​o​n​}​<​/​c​o​d​e​>​
​•​ ​Т​е​к​у​щ​а​я​ ​в​е​р​с​и​я​ ​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​<​a​ ​c​l​a​s​s​=​"​t​g​-​t​e​x​t​-​l​i​n​k​"​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​b​u​n​.​s​h​"​>​B​u​n​<​/​a​>​<​/​b​>​ ​—​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​v​{​b​u​n​_​v​e​r​s​i​o​n​}​<​/​c​o​d​e​>
	 * @param {string} bun_version
	 * @param {string} version
	 */
	start_command: RequiredParams<'bun_version' | 'version'>
	/**
	 * В​ы​ ​б​ы​л​и​ ​у​с​п​е​ш​н​о​ ​з​а​р​е​г​и​с​т​р​и​р​о​в​а​н​ы​ ​п​о​ ​р​е​ф​ф​е​р​а​л​ь​н​о​й​ ​с​с​ы​л​к​е​!​
​
​•​ ​В​а​ш​ ​р​е​ф​ф​е​р​а​л​:​ ​<​a​ ​c​l​a​s​s​=​"​t​g​-​t​e​x​t​-​m​e​n​t​i​o​n​"​ ​h​r​e​f​=​"​t​g​:​/​/​u​s​e​r​?​i​d​=​{​r​e​f​f​e​r​a​l​_​i​d​}​"​>​{​r​e​f​f​e​r​a​l​_​n​a​m​e​}​<​/​a​>​ ​[​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​r​e​f​f​e​r​a​l​_​i​d​}​<​/​c​o​d​e​>​]
	 * @param {string} refferal_id
	 * @param {string} refferal_name
	 */
	start_refferal_command: RequiredParams<'refferal_id' | 'refferal_id' | 'refferal_name'>
}

export type TranslationFunctions = {
	/**
	 * Добро пожаловать!

• Текущая версия <b class="tg-bold"><a class="tg-text-link" href="https://github.com/MSD-Incorporated/MSDBotTelegram">MSDBot</a></b> — <code class="tg-code">{version}</code>
• Текущая версия <b class="tg-bold"><a class="tg-text-link" href="https://bun.sh">Bun</a></b> — <code class="tg-code">v{bun_version}</code>
	 */
	start_command: (arg: { bun_version: string, version: string }) => LocalizedString
	/**
	 * Вы были успешно зарегистрированы по рефферальной ссылке!

• Ваш рефферал: <a class="tg-text-mention" href="tg://user?id={refferal_id}">{refferal_name}</a> [<code class="tg-code">{refferal_id}</code>]
	 */
	start_refferal_command: (arg: { refferal_id: string, refferal_name: string }) => LocalizedString
}

export type Formatters = {}
