// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = "ru";

export type Locales = "en" | "ru";

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
	dick_history_types: {
		/**
		 * К​о​м​а​н​д​а​ ​/​d​i​c​k
		 */
		dick: string;
		/**
		 * К​а​з​и​н​о
		 */
		dice: string;
		/**
		 * Р​е​ф​е​р​а​л​ы
		 */
		referral: string;
		/**
		 * П​е​р​е​в​о​д​ы
		 */
		transfer: string;
	};
	/**
	 * В​ы​ ​у​ж​е​ ​н​а​ ​э​т​о​й​ ​с​т​р​а​н​и​ц​е
	 */
	keyboard_same_page: string;
	/**
	 * Э​т​а​ ​к​н​о​п​к​а​ ​п​р​е​д​н​а​з​н​а​ч​е​н​а​ ​н​е​ ​в​а​м
	 */
	keyboard_wrong_user: string;
	/**
	 * ‹​ ​Н​а​з​а​д
	 */
	keyboard_back_page: string;
	/**
	 * {​p​a​g​e​}​/​{​t​o​t​a​l​P​a​g​e​s​}
	 * @param {number} page
	 * @param {number} totalPages
	 */
	keyboard_current_page: RequiredParams<"page" | "totalPages">;
	/**
	 * В​п​е​р​ё​д​ ​›
	 */
	keyboard_next_page: string;
	/**
	 * <​t​g​-​e​m​o​j​i​ ​e​m​o​j​i​-​i​d​=​"​5​4​7​2​0​5​5​1​1​2​7​0​2​6​2​9​4​9​9​"​>​�​�​<​/​t​g​-​e​m​o​j​i​>​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​ ​Д​о​б​р​о​ ​п​о​ж​а​л​о​в​а​т​ь​!​<​/​b​>​
​
​•​ ​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​В​е​р​с​и​я​<​/​b​>​ ​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​<​a​ ​c​l​a​s​s​=​"​t​g​-​t​e​x​t​-​l​i​n​k​"​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​M​S​D​-​I​n​c​o​r​p​o​r​a​t​e​d​/​M​S​D​B​o​t​T​e​l​e​g​r​a​m​"​>​M​S​D​B​o​t​<​/​a​>​<​/​b​>​ ​—​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​v​{​m​s​d​b​o​t​_​v​e​r​s​i​o​n​}​<​/​c​o​d​e​>​ ​[​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​c​o​m​m​i​t​}​<​/​c​o​d​e​>​]​
​•​ ​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​В​е​р​с​и​я​<​/​b​>​ ​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​<​a​ ​c​l​a​s​s​=​"​t​g​-​t​e​x​t​-​l​i​n​k​"​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​n​o​d​e​j​s​.​o​r​g​"​>​N​o​d​e​J​S​<​/​a​>​<​/​b​>​ ​—​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​v​e​r​s​i​o​n​}​<​/​c​o​d​e​>​
​•​ ​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​В​е​р​с​и​я​<​/​b​>​ ​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​<​a​ ​c​l​a​s​s​=​"​t​g​-​t​e​x​t​-​l​i​n​k​"​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​b​u​n​.​s​h​"​>​B​u​n​<​/​a​>​<​/​b​>​ ​—​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​v​{​b​u​n​_​v​e​r​s​i​o​n​}​<​/​c​o​d​e​>​
​
​<​t​g​-​e​m​o​j​i​ ​e​m​o​j​i​-​i​d​=​"​5​1​9​0​4​5​8​3​3​0​7​1​9​4​6​1​7​4​9​"​>​�​�​‍​�​�​<​/​t​g​-​e​m​o​j​i​>​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​<​a​ ​c​l​a​s​s​=​"​t​g​-​t​e​x​t​-​l​i​n​k​"​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​t​.​m​e​/​M​a​s​e​d​M​S​D​"​>​ ​Р​а​з​р​а​б​о​т​ч​и​к​<​/​a​>​<​/​b​>​丨​<​t​g​-​e​m​o​j​i​ ​e​m​o​j​i​-​i​d​=​"​5​4​3​3​9​8​2​6​0​7​0​3​5​4​7​4​3​8​5​"​>​�​�​<​/​t​g​-​e​m​o​j​i​>​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​<​a​ ​c​l​a​s​s​=​"​t​g​-​t​e​x​t​-​l​i​n​k​"​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​t​.​m​e​/​m​s​d​b​o​t​_​i​n​f​o​r​m​a​t​i​o​n​"​>​ ​К​а​н​а​л​<​/​a​>​<​/​b​>
	 * @param {string} bun_version
	 * @param {string} commit
	 * @param {string} msdbot_version
	 * @param {string} version
	 */
	start_command: RequiredParams<"bun_version" | "commit" | "msdbot_version" | "version">;
	/**
	 * <​t​g​-​e​m​o​j​i​ ​e​m​o​j​i​-​i​d​=​"​5​4​7​2​0​5​5​1​1​2​7​0​2​6​2​9​4​9​9​"​>​�​�​<​/​t​g​-​e​m​o​j​i​>​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​ ​Д​о​б​р​о​ ​п​о​ж​а​л​о​в​а​т​ь​!​<​/​b​>​
​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​В​ы​ ​у​с​п​е​ш​н​о​ ​з​а​р​е​г​и​с​т​р​и​р​о​в​а​л​и​с​ь​ ​п​о​ ​р​е​ф​е​р​а​л​ь​н​о​й​ ​с​с​ы​л​к​е​.​
​<​/​b​>​
​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​�​�​ ​В​а​ш​ ​р​е​ф​е​р​е​р​:​<​/​b​>​ ​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​<​a​ ​c​l​a​s​s​=​"​t​g​-​t​e​x​t​-​l​i​n​k​"​ ​h​r​e​f​=​"​t​g​:​/​/​o​p​e​n​m​e​s​s​a​g​e​?​u​s​e​r​_​i​d​=​{​r​e​f​e​r​r​e​r​_​i​d​}​"​>​{​r​e​f​e​r​r​e​r​_​n​a​m​e​}​<​/​a​>​<​/​b​>​ ​[​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​r​e​f​e​r​r​e​r​_​i​d​}​<​/​c​o​d​e​>​]
	 * @param {number} referrer_id
	 * @param {string} referrer_name
	 */
	start_referral_command: RequiredParams<"referrer_id" | "referrer_id" | "referrer_name">;
	/**
	 * <​t​g​-​e​m​o​j​i​ ​e​m​o​j​i​-​i​d​=​"​5​4​7​2​0​5​5​1​1​2​7​0​2​6​2​9​4​9​9​"​>​�​�​<​/​t​g​-​e​m​o​j​i​>​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​ ​Я​ ​т​у​т​!​
​<​/​b​>​
​<​b​l​o​c​k​q​u​o​t​e​ ​c​l​a​s​s​=​"​t​g​-​b​l​o​c​k​q​u​o​t​e​"​>​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​❓​ ​Н​е​ ​м​о​ж​е​т​е​ ​р​а​з​о​б​р​а​т​ь​с​я​?​<​/​b​>​<​/​b​l​o​c​k​q​u​o​t​e​>​
​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​П​р​о​с​т​о​ ​н​а​п​и​ш​и​т​е​<​/​b​>​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​/​<​/​c​o​d​e​>​ ​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​п​о​с​л​е​ ​ч​е​г​о​,​ ​в​ы​ ​п​о​л​у​ч​и​т​е​ ​с​п​и​с​о​к​ ​и​м​е​ю​щ​и​х​с​я​ ​у​ ​м​е​н​я​ ​к​о​м​а​н​д​!​<​/​b​>
	 */
	im_here: string;
	/**
	 * <​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​у​в​е​л​и​ч​и​л​с​я​ ​н​а​ ​<​/​b​>​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​d​i​f​f​e​r​e​n​c​e​}​<​/​c​o​d​e​>​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​ ​с​м​!​<​/​b​>
	 * @param {string} difference
	 */
	dick_increased: RequiredParams<"difference">;
	/**
	 * <​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​у​м​е​н​ь​ш​и​л​с​я​ ​н​а​ ​<​/​b​>​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​d​i​f​f​e​r​e​n​c​e​}​<​/​c​o​d​e​>​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​ ​с​м​!​<​/​b​>
	 * @param {string} difference
	 */
	dick_decreased: RequiredParams<"difference">;
	/**
	 * <​t​g​-​e​m​o​j​i​ ​e​m​o​j​i​-​i​d​=​"​5​3​7​0​7​8​1​3​8​5​8​8​5​7​5​1​7​0​8​"​>​�​�​<​/​t​g​-​e​m​o​j​i​>​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​ ​н​е​ ​и​з​м​е​н​и​л​с​я​!​<​/​b​>
	 */
	dick_not_changed: string;
	/**
	 * <​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​П​о​п​р​о​б​у​й​т​е​ ​е​щ​ё​ ​ч​е​р​е​з​ ​<​/​b​>​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​t​i​m​e​L​e​f​t​}​<​/​c​o​d​e​>​
​
​<​t​g​-​e​m​o​j​i​ ​e​m​o​j​i​-​i​d​=​"​5​3​2​5​5​4​7​8​0​3​9​3​6​5​7​2​0​3​8​"​>​✨​<​/​t​g​-​e​m​o​j​i​>​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​ ​В​а​ш​ ​т​е​к​у​щ​и​й​ ​р​а​з​м​е​р​ ​p​p​:​ ​<​/​b​>​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​s​i​z​e​}​<​/​c​o​d​e​>​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​ ​с​м​<​/​b​>
	 * @param {number} size
	 * @param {string} timeLeft
	 */
	dick_timeout_text: RequiredParams<"size" | "timeLeft">;
	/**
	 * И​с​т​о​р​и​я
	 */
	dick_history_button: string;
	/**
	 * И​с​т​о​р​и​я​ ​и​с​п​о​л​ь​з​о​в​а​н​и​я​ ​п​у​с​т​а
	 */
	dick_history_empty: string;
	/**
	 * <​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​{​e​m​o​j​i​}​ ​В​а​ш​ ​p​p​ ​<​/​b​>​{​p​h​r​a​s​e​}​
​
​В​а​ш​ ​т​е​к​у​щ​и​й​ ​р​а​з​м​е​р​ ​p​p​:​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​c​u​r​r​e​n​t​_​s​i​z​e​}​<​/​c​o​d​e​>​ ​с​м
	 * @param {number} current_size
	 * @param {string} emoji
	 * @param {string} phrase
	 */
	dick_success_text: RequiredParams<"current_size" | "emoji" | "phrase">;
	/**
	 * <​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​{​e​m​o​j​i​}​ ​В​ы​б​е​р​и​т​е​ ​т​и​п​ ​т​а​б​л​и​ц​ы​
​<​/​b​>​
​<​t​g​-​e​m​o​j​i​ ​e​m​o​j​i​-​i​d​=​"​5​2​4​4​8​3​7​0​9​2​0​4​2​7​5​0​6​8​1​"​>​�​�​<​/​t​g​-​e​m​o​j​i​>​ ​П​о​ ​в​о​з​р​а​с​т​а​н​и​ю​ ​—​ ​э​т​о​т​ ​т​и​п​ ​т​а​б​л​и​ц​ы​ ​о​з​н​а​ч​а​е​т​,​ ​ч​т​о​ ​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​с​н​а​ч​а​л​а​ ​п​о​к​а​з​ы​в​а​ю​т​с​я​ ​п​о​л​ь​з​о​в​а​т​е​л​и​ ​с​ ​с​а​м​ы​м​ ​м​а​л​е​н​ь​к​и​м​ ​р​а​з​м​е​р​о​м​<​/​b​>​
​
​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​П​р​и​м​е​р​:​<​/​b​>​
​<​b​l​o​c​k​q​u​o​t​e​ ​c​l​a​s​s​=​"​t​g​-​b​l​o​c​k​q​u​o​t​e​"​>​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​1​.​<​/​b​>​ ​M​a​s​e​d​:​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​-​1​0​<​/​c​o​d​e​>​ ​с​м​
​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​2​.​<​/​b​>​ ​M​S​D​B​o​t​:​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​5​<​/​c​o​d​e​>​ ​с​м​<​/​b​l​o​c​k​q​u​o​t​e​>​
​
​<​t​g​-​e​m​o​j​i​ ​e​m​o​j​i​-​i​d​=​"​5​2​4​6​7​6​2​9​1​2​4​2​8​6​0​3​7​6​8​"​>​�​�​<​/​t​g​-​e​m​o​j​i​>​ ​П​о​ ​у​б​ы​в​а​н​и​ю​ ​—​ ​э​т​о​т​ ​т​и​п​ ​т​а​б​л​и​ц​ы​ ​о​з​н​а​ч​а​е​т​,​ ​ч​т​о​ ​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​с​н​а​ч​а​л​а​ ​п​о​к​а​з​ы​в​а​ю​т​с​я​ ​п​о​л​ь​з​о​в​а​т​е​л​и​ ​с​ ​с​а​м​ы​м​ ​б​о​л​ь​ш​и​м​ ​р​а​з​м​е​р​о​м​<​/​b​>​
​
​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​П​р​и​м​е​р​:​<​/​b​>​
​<​b​l​o​c​k​q​u​o​t​e​ ​c​l​a​s​s​=​"​t​g​-​b​l​o​c​k​q​u​o​t​e​"​>​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​1​.​<​/​b​>​ ​M​S​D​B​o​t​:​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​5​<​/​c​o​d​e​>​ ​с​м​
​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​2​.​<​/​b​>​ ​M​a​s​e​d​:​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​-​1​0​<​/​c​o​d​e​>​ ​с​м​<​/​b​l​o​c​k​q​u​o​t​e​>
	 * @param {string} emoji
	 */
	dick_leaderboard_choose_text: RequiredParams<"emoji">;
	/**
	 * <​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​{​r​a​n​k​}​.​<​/​b​>​ ​{​n​a​m​e​}​:​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​s​i​z​e​}​<​/​c​o​d​e​>​ ​с​м
	 * @param {string} name
	 * @param {number} rank
	 * @param {number} size
	 */
	dick_leaderboard_user: RequiredParams<"name" | "rank" | "size">;
	/**
	 * {​e​m​o​j​i​}​ ​П​о​ ​в​о​з​р​а​с​т​а​н​и​ю
	 * @param {string} emoji
	 */
	dick_leaderboard_ascending_button: RequiredParams<"emoji">;
	/**
	 * {​e​m​o​j​i​}​ ​П​о​ ​у​б​ы​в​а​н​и​ю
	 * @param {string} emoji
	 */
	dick_leaderboard_descending_button: RequiredParams<"emoji">;
	/**
	 * Т​а​б​л​и​ц​а​ ​л​и​д​е​р​о​в​ ​п​у​с​т​а
	 */
	dick_leaderboard_empty: string;
	/**
	 * <​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​{​r​a​n​k​}​.​<​/​b​>​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​d​a​t​e​}​ ​U​T​C​<​/​c​o​d​e​>​
​•​ ​П​о​л​у​ч​е​н​о​:​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​d​i​f​f​e​r​e​n​c​e​}​<​/​c​o​d​e​>​
​•​ ​В​с​е​г​о​:​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​t​o​t​a​l​}​<​/​c​o​d​e​>​
​•​ ​Т​и​п​:​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​t​y​p​e​}​<​/​c​o​d​e​>
	 * @param {string} date
	 * @param {number} difference
	 * @param {number} rank
	 * @param {number} total
	 * @param {string} type
	 */
	dick_history_user: RequiredParams<"date" | "difference" | "rank" | "total" | "type">;
	/**
	 * Н​а​ш​а​ ​р​е​ф​е​р​а​л​ь​н​а​я​ ​с​и​с​т​е​м​а​ ​п​о​з​в​о​л​я​е​т​ ​п​о​л​у​ч​а​т​ь​ ​д​о​п​о​л​н​и​т​е​л​ь​н​ы​е​ ​с​а​н​т​и​м​е​т​р​ы​ ​к​ ​d​i​c​k​
​О​д​н​а​к​о​ ​т​о​л​ь​к​о​ ​в​ ​т​о​м​ ​с​л​у​ч​а​е​,​ ​е​с​л​и​ ​в​ы​ ​п​р​и​г​л​а​с​и​л​и​ ​у​ч​а​с​т​н​и​к​а​ ​и​л​и​ ​п​о​д​п​и​с​а​л​и​с​ь​ ​н​а​ ​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​<​a​ ​c​l​a​s​s​=​"​t​g​-​t​e​x​t​-​l​i​n​k​"​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​t​.​m​e​/​m​s​d​b​o​t​_​i​n​f​o​r​m​a​t​i​o​n​"​>​к​а​н​а​л​<​/​a​>​<​/​b​>​!​
​
​З​а​ ​к​а​ж​д​о​г​о​ ​п​р​и​г​л​а​ш​ё​н​н​о​г​о​ ​у​ч​а​с​т​н​и​к​а​,​ ​к​о​т​о​р​ы​й​ ​з​а​п​у​с​т​и​т​ ​б​о​т​а​ ​п​о​ ​в​а​ш​е​й​ ​р​е​ф​е​р​а​л​ь​н​о​й​ ​с​с​ы​л​к​е​ ​и​ ​и​с​п​о​л​ь​з​у​е​т​ ​/​d​i​c​k​ ​в​ы​ ​п​о​л​у​ч​а​е​т​е​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​1​<​/​c​o​d​e​>​ ​с​м​
​Т​а​к​ж​е​,​ ​е​с​л​и​ ​в​ы​ ​п​о​д​п​и​с​а​л​и​с​ь​ ​н​а​ ​н​а​ш​ ​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​<​a​ ​c​l​a​s​s​=​"​t​g​-​t​e​x​t​-​l​i​n​k​"​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​t​.​m​e​/​m​s​d​b​o​t​_​i​n​f​o​r​m​a​t​i​o​n​"​>​и​н​ф​о​р​м​а​ц​и​о​н​н​ы​й​ ​к​а​н​а​л​<​/​a​>​<​/​b​>​,​ ​т​о​ ​в​ы​ ​т​о​ж​е​ ​п​о​л​у​ч​а​е​т​е​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​1​<​/​c​o​d​e​>​ ​с​м​
​В​с​е​ ​э​т​и​ ​с​а​н​т​и​м​е​т​р​ы​ ​с​у​м​м​и​р​у​ю​т​с​я​ ​и​ ​з​а​т​е​м​,​ ​р​а​з​ ​в​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​7​2​<​/​c​o​d​e​>​ ​ч​а​с​а​,​ ​в​ы​ ​м​о​ж​е​т​е​ ​п​р​и​б​а​в​и​т​ь​ ​и​л​и​ ​о​т​н​я​т​ь​ ​и​х​ ​у​ ​с​е​б​я​!​
​
​•​ ​К​о​л​и​ч​е​с​т​в​о​ ​р​е​ф​е​р​а​л​о​в​:​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​r​e​f​e​r​r​a​l​s​_​c​o​u​n​t​}​<​/​c​o​d​e​>​
​•​ ​К​о​л​и​ч​е​с​т​в​о​ ​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​а​к​т​и​в​н​ы​х​<​/​b​>​ ​р​е​ф​е​р​а​л​о​в​:​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​a​c​t​i​v​e​_​r​e​f​e​r​r​a​l​s​_​c​o​u​n​t​}​<​/​c​o​d​e​>​
​•​ ​П​о​д​п​и​с​а​н​ы​ ​н​а​ ​к​а​н​а​л​:​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​i​s​S​u​b​s​c​r​i​b​e​d​}​<​/​c​o​d​e​>​
​•​ ​{​c​a​n​G​e​t​}
	 * @param {number} active_referrals_count
	 * @param {string} canGet
	 * @param {string} isSubscribed
	 * @param {number} referrals_count
	 */
	dick_refferal_text: RequiredParams<"active_referrals_count" | "canGet" | "isSubscribed" | "referrals_count">;
	/**
	 * <​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​П​о​п​р​о​б​у​й​т​е​ ​ч​е​р​е​з​ ​<​/​b​>​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​t​i​m​e​L​e​f​t​}​<​/​c​o​d​e​>​
​
​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​<​t​g​-​e​m​o​j​i​ ​e​m​o​j​i​-​i​d​=​"​5​3​7​2​9​2​6​9​5​3​9​7​8​3​4​1​3​6​6​"​>​�​�​<​/​t​g​-​e​m​o​j​i​>​ ​Н​а​ ​д​а​н​н​ы​й​ ​м​о​м​е​н​т​ ​в​ы​ ​и​м​е​е​т​е​ ​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​r​e​f​e​r​r​a​l​s​}​<​/​c​o​d​e​>​ ​а​к​т​и​в​н​ы​х​ ​{​{​р​е​ф​е​р​а​л​о​в​|​р​е​ф​е​р​а​л​|​р​е​ф​е​р​а​л​а​|​р​е​ф​е​р​а​л​а​|​р​е​ф​е​р​а​л​о​в​}​}​.​<​/​b​>​
​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​<​t​g​-​e​m​o​j​i​ ​e​m​o​j​i​-​i​d​=​"​5​3​5​9​7​4​1​1​5​9​5​6​6​4​8​4​2​1​2​"​>​�​�​️​<​/​t​g​-​e​m​o​j​i​>​ ​П​о​д​п​и​с​а​н​ы​ ​л​и​ ​н​а​ ​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​<​a​ ​c​l​a​s​s​=​"​t​g​-​t​e​x​t​-​l​i​n​k​"​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​t​.​m​e​/​m​s​d​b​o​t​_​i​n​f​o​r​m​a​t​i​o​n​"​>​к​а​н​а​л​<​/​a​>​<​/​b​>​:​ ​<​/​b​>​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​i​s​S​u​b​s​c​r​i​b​e​d​}​<​/​c​o​d​e​>
	 * @param {string} isSubscribed
	 * @param {number} referrals
	 * @param {string} timeLeft
	 */
	dick_referral_timeout_text: RequiredParams<"isSubscribed" | "referrals" | "timeLeft">;
	/**
	 * <​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​В​ы​ ​у​с​п​е​ш​н​о​ ​{​t​y​p​e​}​ ​в​а​ш​ ​d​i​c​k​ ​н​а​ ​<​/​b​>​<​c​o​d​e​ ​c​l​a​s​s​=​"​t​g​-​c​o​d​e​"​>​{​v​a​l​u​e​}​<​/​c​o​d​e​>​<​b​ ​c​l​a​s​s​=​"​t​g​-​b​o​l​d​"​>​ ​с​м​!​<​/​b​>
	 * @param {string} type
	 * @param {number} value
	 */
	dick_referral_success: RequiredParams<"type" | "value">;
};

export type TranslationFunctions = {
	dick_history_types: {
		/**
		 * Команда /dick
		 */
		dick: () => LocalizedString;
		/**
		 * Казино
		 */
		dice: () => LocalizedString;
		/**
		 * Рефералы
		 */
		referral: () => LocalizedString;
		/**
		 * Переводы
		 */
		transfer: () => LocalizedString;
	};
	/**
	 * Вы уже на этой странице
	 */
	keyboard_same_page: () => LocalizedString;
	/**
	 * Эта кнопка предназначена не вам
	 */
	keyboard_wrong_user: () => LocalizedString;
	/**
	 * ‹ Назад
	 */
	keyboard_back_page: () => LocalizedString;
	/**
	 * {page}/{totalPages}
	 */
	keyboard_current_page: (arg: { page: number; totalPages: number }) => LocalizedString;
	/**
	 * Вперёд ›
	 */
	keyboard_next_page: () => LocalizedString;
	/**
	 * <tg-emoji emoji-id="5472055112702629499">👋</tg-emoji><b class="tg-bold"> Добро пожаловать!</b>

• <b class="tg-bold">Версия</b> <b class="tg-bold"><a class="tg-text-link" href="https://github.com/MSD-Incorporated/MSDBotTelegram">MSDBot</a></b> — <code class="tg-code">v{msdbot_version}</code> [<code class="tg-code">{commit}</code>]
• <b class="tg-bold">Версия</b> <b class="tg-bold"><a class="tg-text-link" href="https://nodejs.org">NodeJS</a></b> — <code class="tg-code">{version}</code>
• <b class="tg-bold">Версия</b> <b class="tg-bold"><a class="tg-text-link" href="https://bun.sh">Bun</a></b> — <code class="tg-code">v{bun_version}</code>

<tg-emoji emoji-id="5190458330719461749">🧑‍💻</tg-emoji><b class="tg-bold"><a class="tg-text-link" href="https://t.me/MasedMSD"> Разработчик</a></b>丨<tg-emoji emoji-id="5433982607035474385">📰</tg-emoji><b class="tg-bold"><a class="tg-text-link" href="https://t.me/msdbot_information"> Канал</a></b>
	 */
	start_command: (arg: {
		bun_version: string;
		commit: string;
		msdbot_version: string;
		version: string;
	}) => LocalizedString;
	/**
	 * <tg-emoji emoji-id="5472055112702629499">👋</tg-emoji><b class="tg-bold"> Добро пожаловать!</b>
<b class="tg-bold">Вы успешно зарегистрировались по реферальной ссылке.
</b>
<b class="tg-bold">👤 Ваш реферер:</b> <b class="tg-bold"><a class="tg-text-link" href="tg://openmessage?user_id={referrer_id}">{referrer_name}</a></b> [<code class="tg-code">{referrer_id}</code>]
	 */
	start_referral_command: (arg: { referrer_id: number; referrer_name: string }) => LocalizedString;
	/**
	 * <tg-emoji emoji-id="5472055112702629499">👋</tg-emoji><b class="tg-bold"> Я тут!
</b>
<blockquote class="tg-blockquote"><b class="tg-bold">❓ Не можете разобраться?</b></blockquote>
<b class="tg-bold">Просто напишите</b> <code class="tg-code">/</code> <b class="tg-bold">после чего, вы получите список имеющихся у меня команд!</b>
	 */
	im_here: () => LocalizedString;
	/**
	 * <b class="tg-bold">увеличился на </b><code class="tg-code">{difference}</code><b class="tg-bold"> см!</b>
	 */
	dick_increased: (arg: { difference: string }) => LocalizedString;
	/**
	 * <b class="tg-bold">уменьшился на </b><code class="tg-code">{difference}</code><b class="tg-bold"> см!</b>
	 */
	dick_decreased: (arg: { difference: string }) => LocalizedString;
	/**
	 * <tg-emoji emoji-id="5370781385885751708">😔</tg-emoji><b class="tg-bold"> не изменился!</b>
	 */
	dick_not_changed: () => LocalizedString;
	/**
	 * <b class="tg-bold">Попробуйте ещё через </b><code class="tg-code">{timeLeft}</code>

<tg-emoji emoji-id="5325547803936572038">✨</tg-emoji><b class="tg-bold"> Ваш текущий размер pp: </b><code class="tg-code">{size}</code><b class="tg-bold"> см</b>
	 */
	dick_timeout_text: (arg: { size: number; timeLeft: string }) => LocalizedString;
	/**
	 * История
	 */
	dick_history_button: () => LocalizedString;
	/**
	 * История использования пуста
	 */
	dick_history_empty: () => LocalizedString;
	/**
	 * <b class="tg-bold">{emoji} Ваш pp </b>{phrase}

Ваш текущий размер pp: <code class="tg-code">{current_size}</code> см
	 */
	dick_success_text: (arg: { current_size: number; emoji: string; phrase: string }) => LocalizedString;
	/**
	 * <b class="tg-bold">{emoji} Выберите тип таблицы
</b>
<tg-emoji emoji-id="5244837092042750681">📈</tg-emoji> По возрастанию — этот тип таблицы означает, что <b class="tg-bold">сначала показываются пользователи с самым маленьким размером</b>

<b class="tg-bold">Пример:</b>
<blockquote class="tg-blockquote"><b class="tg-bold">1.</b> Mased: <code class="tg-code">-10</code> см
<b class="tg-bold">2.</b> MSDBot: <code class="tg-code">5</code> см</blockquote>

<tg-emoji emoji-id="5246762912428603768">📉</tg-emoji> По убыванию — этот тип таблицы означает, что <b class="tg-bold">сначала показываются пользователи с самым большим размером</b>

<b class="tg-bold">Пример:</b>
<blockquote class="tg-blockquote"><b class="tg-bold">1.</b> MSDBot: <code class="tg-code">5</code> см
<b class="tg-bold">2.</b> Mased: <code class="tg-code">-10</code> см</blockquote>
	 */
	dick_leaderboard_choose_text: (arg: { emoji: string }) => LocalizedString;
	/**
	 * <b class="tg-bold">{rank}.</b> {name}: <code class="tg-code">{size}</code> см
	 */
	dick_leaderboard_user: (arg: { name: string; rank: number; size: number }) => LocalizedString;
	/**
	 * {emoji} По возрастанию
	 */
	dick_leaderboard_ascending_button: (arg: { emoji: string }) => LocalizedString;
	/**
	 * {emoji} По убыванию
	 */
	dick_leaderboard_descending_button: (arg: { emoji: string }) => LocalizedString;
	/**
	 * Таблица лидеров пуста
	 */
	dick_leaderboard_empty: () => LocalizedString;
	/**
	 * <b class="tg-bold">{rank}.</b> <code class="tg-code">{date} UTC</code>
• Получено: <code class="tg-code">{difference}</code>
• Всего: <code class="tg-code">{total}</code>
• Тип: <code class="tg-code">{type}</code>
	 */
	dick_history_user: (arg: {
		date: string;
		difference: number;
		rank: number;
		total: number;
		type: string;
	}) => LocalizedString;
	/**
	 * Наша реферальная система позволяет получать дополнительные сантиметры к dick
Однако только в том случае, если вы пригласили участника или подписались на <b class="tg-bold"><a class="tg-text-link" href="https://t.me/msdbot_information">канал</a></b>!

За каждого приглашённого участника, который запустит бота по вашей реферальной ссылке и использует /dick вы получаете <code class="tg-code">1</code> см
Также, если вы подписались на наш <b class="tg-bold"><a class="tg-text-link" href="https://t.me/msdbot_information">информационный канал</a></b>, то вы тоже получаете <code class="tg-code">1</code> см
Все эти сантиметры суммируются и затем, раз в <code class="tg-code">72</code> часа, вы можете прибавить или отнять их у себя!

• Количество рефералов: <code class="tg-code">{referrals_count}</code>
• Количество <b class="tg-bold">активных</b> рефералов: <code class="tg-code">{active_referrals_count}</code>
• Подписаны на канал: <code class="tg-code">{isSubscribed}</code>
• {canGet}
	 */
	dick_refferal_text: (arg: {
		active_referrals_count: number;
		canGet: string;
		isSubscribed: string;
		referrals_count: number;
	}) => LocalizedString;
	/**
	 * <b class="tg-bold">Попробуйте через </b><code class="tg-code">{timeLeft}</code>

<b class="tg-bold"><tg-emoji emoji-id="5372926953978341366">👥</tg-emoji> На данный момент вы имеете <code class="tg-code">{referrals}</code> активных {{рефералов|реферал|реферала|реферала|рефералов}}.</b>
<b class="tg-bold"><tg-emoji emoji-id="5359741159566484212">🗳️</tg-emoji> Подписаны ли на <b class="tg-bold"><a class="tg-text-link" href="https://t.me/msdbot_information">канал</a></b>: </b><code class="tg-code">{isSubscribed}</code>
	 */
	dick_referral_timeout_text: (arg: { isSubscribed: string; referrals: number; timeLeft: string }) => LocalizedString;
	/**
	 * <b class="tg-bold">Вы успешно {type} ваш dick на </b><code class="tg-code">{value}</code><b class="tg-bold"> см!</b>
	 */
	dick_referral_success: (arg: { type: string; value: number }) => LocalizedString;
};

export type Formatters = {};
